### ISSUE TITLE
Android ERG Contro

### ISSUE THREAD

**Issue by SevBob** [kinetic-fit/fit-android-issues#2]
Did a couple workouts in Android, wasn't getting ERG control in any of them.  Power data was about 80 watts low as compared to my Garmin pedals.

**Comment by lexicalninja** [comment]
Please answer the following questions to help me out: 
We may need to open an issue on the firmware project for the power data

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Version [e.g. 2.0.1]

**Trainer (please complete the following information):**
- Trainer: [e.g. SmartControl 1]
- Firmware Version [e.g. v2.1]

**Additional context**
Add any other context about the problem here.

**Comment by lexicalninja** [comment]
added to beta release
