### ISSUE TITLE
ERG prompt displays target power with the intensity slider at 0.

### ISSUE THREAD

**Issue by SevBob** [kinetic-fit/fit-android-issues#3]
If you move the slider to adjust the targets, the power target displayed is incorrect.

**Comment by lexicalninja** [comment]
@SevBob What screen is this on? 
What do you mean by the power target is incorrect? The power target shown in a workout or where?

**Comment by SevBob** [comment]
During the transitions from one target to the next there is a box that pops up that displays your power and the target for the next block.  It will display accurate power provided you haven’t touched the intensity slider.  If you have moved the slider, the new target is not displayed correctly, it displays what your target would be with the slider at 0.  It’s in any workout with ERG control, just start one, tickle the slider to adjust your target, then let the w/o run until you hit one of these transitions.

S

**Comment by lexicalninja** [comment]
What slider?

**Comment by lexicalninja** [comment]
OK, I've got the issue templates done, please fill one out for this so that I can read through it and try and get this fixed. It is like related to #2 , but we will leave it separate for now in case it needs to be a feature request. 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Version [e.g. 2.0.1]

**Trainer (please complete the following information):**
- Trainer: [e.g. SmartControl 1]
- Firmware Version [e.g. v2.1]

**Additional context**
Add any other context about the problem here.

**Comment by SevBob** [comment]
The Intensity slider in the sensor settings menu, it shifts the target power up or down as needed.

**Comment by lexicalninja** [comment]
added to beta release
