### ISSUE TITLE
Can't "re-ride" workout from workout review screen

### ISSUE THREAD

**Issue by jacco411** [kinetic-fit/fit-android-issues#30]
**Describe the bug**
When looking at the session analysis, the button on the bottom right for "re -ride" did not take you the same workout. It automatically takes you to a free ride session.

**To Reproduce**
1. Go to any session analysis
2. Click on 're-ride'
3. See error 

**Expected behavior**
To re-ride the same workout.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy s9+
 - OS: Android 10
 - Kinetic Fit Version 2.5.4

**Trainer (please complete the following information):**
- Trainer: rock n roll control
- Firmware Version 1.3

**Comment by lexicalninja** [comment]
Thanks. This should be an easy fix, I will try and get it cleared up this week

**Comment by lexicalninja** [comment]
It was, in fact, an easy fix. I will push this out with the next release. You should see it next week in the update. I will not be pushing an update until Monday next week because I am making some substantial under the hood changes and I don't want to break it going into the weekend and not be able to fix things quickly. Let me know if you see the fix next week

**Comment by lexicalninja** [comment]
@jacco411 Please take a second to see if this works correctly after you receive the 2.5.6 (237) update. Thanks for reporting this.
