### ISSUE TITLE
Notice badge, but can't find what it is alerting about

### ISSUE THREAD

**Issue by duanegran** [kinetic-fit/fit-android-issues#5]
**Describe the bug**
I see a number 1 in a circle on the Fit App icon, which seems to mean there is some sort of notice.  I launch the app and I can't find the notice anywhere in the app.  The only possible indication I have is a system related notice (pull down from top screen) for the Kinetic Sensor Service that says "Kinetic is running in the background to stay connected..."  Is that the notice?  If so, this may be a very "chatty" notice badge that stays around often.  

**Smartphone (please complete the following information):**
 - Device: Samsung 9
 - OS: Android
 - Version 9

**Comment by lexicalninja** [comment]
This is because there is a system notification for android that is required to run background services. The sensor service runs in the background to keep getting data if you switch apps on the phone, so this will need to stay.

The badge is likely from the Samsung launcher and can probably be turned off in settings. This does not show up in some other versions of the OS.
